language: c

compiler: arm-none-eabi-gcc

# Coverity configuration.

addons:

  coverity_scan:

    project:

      name: "eventos-sdk"

      description: "EventOS - Event-driven Operating Systems "

    notification_email: edielsonpf@gmail.com

    build_command_prepend: "cd tests/unit/nxp/lpc1769om13085/makefile"

    build_command: "make all"

    branch_pattern: master


install:

  - mkdir -p "${HOME}"/opt/npm

  - npm config set prefix "${HOME}"/opt/npm

  - echo 'export PATH="${HOME}"/opt/npm/bin:${PATH}' >> "${HOME}"/.profile

  - source "${HOME}"/.profile
  
  - npm install --global xpm

  - mkdir -p "${HOME}"/opt
  
  - cd "${HOME}"/opt/
  
  - wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/7-2017q4/gcc-arm-none-eabi-7-2017-q4-major-linux.tar.bz2?revision=375265d4-e9b5-41c8-bf23-56cbe927e156?product=GNU%20Arm%20Embedded%20Toolchain,64-bit,,Linux,7-2017-q4-major
    
  - tar xjf ~/opt/gcc-arm-none-eabi-7-2017-q4-major-linux.tar.bz2

  - chmod -R -w "${HOME}"/opt/gcc-arm-none-eabi-7-2017-q4-major

 # Export the path and check if gcc has been installed successfully
 
  - echo 'export PATH="${HOME}"/opt/gcc-arm-none-eabi-7-2017-q4-major/bin:${PATH}' >> "${HOME}"/.bashrc
  
  - source "${HOME}"/.bashrc
  
  - arm-none-eabi-gcc --version

  
script:

  # Build the unit tests.

  - cd tests/unit/nxp/lpc1769om13085/makefile

  - make all


  # Execute unit tests.

  