language: c

compiler: arm-none-eabi-gcc

# Coverity configuration.

addons:

  coverity_scan:

    project:

      name: "eventos-sdk"

      description: "EventOS - Event-driven Operating Systems "

    notification_email: edielsonpf@gmail.com

    build_command_prepend: "cd tests/unit/nxp/lpc1769om13085/makefile"

    build_command: "make all"

    branch_pattern: master


install:

  - mkdir -p "${HOME}"/opt/npm

  - npm config set prefix "${HOME}"/opt/npm

  - echo 'export PATH="${HOME}"/opt/npm/bin:${PATH}' >> "${HOME}"/.profile

  - source "${HOME}"/.profile
  
  - npm install --global xpm

  - xpm install --global @gnu-mcu-eclipse/arm-none-eabi-gcc
  
  - tree -L 2 /Users/ilg/Library/xPacks/\@gnu-mcu-eclipse/arm-none-eabi-gcc/7.2.1-1.1/.content/
  
 # Export the path and check if gcc has been installed successfully
 
  - echo 'export PATH="${HOME}"/opt/xPacks/@gnu-mcu-eclipse/arm-none-eabi-gcc/7.2.1-1.1/.content/bin:${PATH}' >> "${HOME}"/.bashrc
  
  - source "${HOME}"/.bashrc
  
  - arm-none-eabi-gcc --version

  
script:

  # Build the unit tests.

  - cd tests/unit/nxp/lpc1769om13085/makefile

  - make all


  # Execute unit tests.

  