language: c

compiler: arm-none-eabi-gcc

# Coverity configuration.

addons:

  coverity_scan:

    project:

      name: "eventos-sdk"

      description: "EventOS - Event-driven Operating Systems "

    notification_email: nobody@gmail.com

    build_command_prepend: "cd tests/unit/nxp/lpc1769om13085/makefile"

    build_command: "make all"

    branch_pattern: master


install:

  - mkdir -p "${HOME}"/opt
  
  - wget https://github.com/gnu-mcu-eclipse/arm-none-eabi-gcc/releases/download/v7.3.1-1.1/gnu-mcu-eclipse-arm-none-eabi-gcc-7.3.1-1.1-20180724-0637-centos64.tgz -O /tmp/gnu-mcu-eclipse-arm-none-eabi-gcc-7.3.1-1.1.tgz
  
  - tar xf /tmp/gnu-mcu-eclipse-arm-none-eabi-gcc-7.3.1-1.1.tgz  -C "${HOME}"/opt

  - chmod -R -w "${HOME}"/opt/GNU MCU Eclipse/ARM Embedded GCC/7.3.1-1.1-20180724-0637
  
 # Export the path and check if gcc has been installed successfully
 
  - export PATH=$PATH:"${HOME}"/opt/GNU MCU Eclipse/ARM Embedded GCC/7.3.1-1.1-20180724-0637/bin/
  
  - arm-none-eabi-gcc --version
  
script:

  # Build the unit tests.

  - cd tests/unit/nxp/lpc1769om13085/makefile

  - make all


  # Execute unit tests.

  