language: c

compiler: arm-none-eabi-gcc

# Coverity configuration.

addons:

  coverity_scan:

    project:

      name: "eventos-sdk"

      description: "EventOS - Event-driven Operating Systems "

    notification_email: edielsonpf@gmail.com

    build_command_prepend: "cd tests/unit/nxp/lpc1769om13085/makefile"

    build_command: "make all"

    branch_pattern: master


install:

  - mkdir -p "${HOME}"/opt/
  
  - cd "${HOME}"/opt/
  
  - wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/7-2018q2/gcc-arm-none-eabi-7-2018-q2-update-linux.tar.bz2?revision=bc2c96c0-14b5-4bb4-9f18-bceb4050fee7?product=GNU%20Arm%20Embedded%20Toolchain,64-bit,,Linux,7-2018-q2-update
    
  - tar xjf ~/opt/gcc-arm-none-eabi-7-2018-q2-update-linux.tar.bz2?revision=bc2c96c0-14b5-4bb4-9f18-bceb4050fee7?product=GNU%20Arm%20Embedded%20Toolchain,64-bit,,Linux,7-2018-q2-update

  - chmod -R -w "${HOME}"/opt/gcc-arm-none-eabi-7-2018-q2-update

 # Export the path and check if gcc has been installed successfully
 
  - echo 'export PATH="${HOME}"/opt/gcc-arm-none-eabi-7-2018-q2-update/bin:${PATH}' >> "${HOME}"/.bashrc
  
  - source "${HOME}"/.bashrc
  
  - arm-none-eabi-gcc --version

  
script:

  # Build the unit tests.

  - cd "${HOME}"/edielsonpf/eventos-sdk/tests/unit/nxp/lpc1769om13085/makefile

  - make all


  # Execute unit tests.

  