language: c

compiler: gcc

# Coverity configuration.

addons:

  coverity_scan:

    project:

      name: "eventos-sdk"

      description: "EventOS - Event-driven Operating Systems "

    notification_email: nobody@gmail.com

    build_command_prepend: "cd tests/unit/nxp/lpc1769om13085/makefile"

    build_command: "make all"

    branch_pattern: master


script:

  # Build the ARM unit tests.

  - cd tests/unit/nxp/lpc1769om13085/makefile

  - make all

  # Build the Linux unit tests.

  - cd tests/unit/pc/linux/

  - make
	
  # Execute unit tests.
 
  - ./EventOS_unit_tests.out 	
  
